# AI CLI Version Compatibility Configuration
# Purpose: Define minimum required versions for each AI CLI tool
# Used by: check-multi-ai-tools.sh, orchestrate-multi-ai.sh

minimum_versions:
  claude: "1.0.0"     # Claude MCP CLI
  gemini: "2.0.0"     # Gemini CLI
  amp: "0.5.0"        # Amp CLI
  qwen: "3.0.0"       # Qwen CLI
  droid: "1.0.0"      # Droid CLI
  codex: "0.47.0"     # Codex CLI (OpenAI)
  cursor: "0.8.0"     # Cursor Agent CLI

# Version extraction commands for each AI
# Format: Command to run that outputs version information
version_commands:
  claude: "claude --version 2>&1 | head -1"
  gemini: "gemini --version 2>&1 | head -1"
  amp: "amp --version 2>&1 | head -1"
  qwen: "qwen --version 2>&1 | head -1"
  droid: "droid --version 2>&1 | head -1"
  codex: "codex --version 2>&1 | head -1"
  cursor: "cursor-agent --version 2>&1 | head -1"

# Version extraction patterns (regex)
# Used to extract version number from command output
version_patterns:
  claude: '\d+\.\d+\.\d+'
  gemini: '\d+\.\d+\.\d+'
  amp: '\d+\.\d+\.\d+'
  qwen: '\d+\.\d+\.\d+'
  droid: '\d+\.\d+\.\d+'
  codex: 'v?(\d+\.\d+\.\d+)'
  cursor: '\d+\.\d+\.\d+'
